In [1]:
import numpy as np
from sklearn.neighbors import KDTree

In [2]:
rng = np.random.RandomState(0)

In [3]:
X = rng.random_sample((10, 3))  # 10 points in 3 dimensions
tree = KDTree(X, leaf_size=2, metric='euclidean') 

In [4]:
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [7]:
dist, ind = tree.query([[0.5, 0.876, 0.123]], k=5)

In [8]:
dist, ind

(array([[0.09894514, 0.4306261 , 0.4492905 , 0.50834606, 0.63892139]]),
 array([[4, 3, 8, 0, 9]], dtype=int64))